### ISSUE TITLE
Wheel: Multiple Value Change on One Swipe

### ISSUE THREAD

**Issue by GioviQ** [CodeBeamOrg/CodeBeam.MudExtensions#51]
I see your commit https://github.com/MudBlazor/MudBlazor/commit/046c46bc6995213d2d6bb230b8766b734fa45d6e so I think you already know that rotating wheels on a smartphone is a very slow experience.

I hope to use MudDateWheelPicker when a swipe will create a little acceleration...

**Comment by mckaragoz** [comment]
It was a limitation due to MudSwipeArea component. With the latest Mud version we merged a PR that added sensitivity to swipe area, so we can also improve swipe behavior on wheels. Yes planned with the first creation of wheel component :) We will add sensitivity directly to the wheel and developers also can set their values, and of course we should change the default.

**Comment by GioviQ** [comment]
@mckaragoz despite the Sensitivity parameter the behaviour is like before: one swipe change only one unit at a time.

I didn't find the button to reopen the issue

**Comment by mckaragoz** [comment]
Ah yes, i know we also should add multiple changes per x sensitivity, but i think it needs some more work. Maybe need to change more codes into core library first.

**Comment by GioviQ** [comment]
A nice feature would be 3D effect like https://demo.mobiscroll.com/fullscreen/datetime/mobile-desktop-usage

**Comment by mckaragoz** [comment]
@GioviQ  I think now we support multiple value change. I already changed the core library to support this feature.

https://user-images.githubusercontent.com/78308169/231787999-e82ef011-584b-4a83-99c2-516d23bf5d44.mp4

Note: It does not really work on real time (ontouchmove) but at least changed multiple value ontouchend. And you can arrange the `Sensitivity` parameter.
